name = "remix-fullstack" #todo need real data
compatibility_date = "2022-06-01"
main = "./build/index.js"

account_id = "93e39c248caa03a01ab11bc4d73875cf" #todo need real data

workers_dev = true

[env.production]
  routes = [
    { pattern = "remix-fullstack.hungvu.work", custom_domain = true }
  ]
  workers_dev = false

[site]
  bucket = "./public"

[build]
  command = "npm run build"

